substitutions:
  _REGION: 'us-central1'        
  _IMAGE_NAME: 'hello-world-image'
  _ARTIFACT_REGISTRY: 'hello-world'
  _SERVICE_ACCOUNT: 'demo-cb@gcp-az-prj-439316.iam.gserviceaccount.com'

serviceAccount: 'projects/gcp-az-prj-439316/serviceAccounts/demo-cb@gcp-az-prj-439316.iam.gserviceaccount.com'

steps:

  # Step 3: Build the Docker image with the commit ID
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY/$_IMAGE_NAME:${SHORT_SHA}'
      - '.'

  # Step 4: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY/$_IMAGE_NAME:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '600s'
