substitutions:
  _REGION: 'us-central1'        
  _IMAGE_NAME: 'hello-world-image'
  _ARTIFACT_REGISTRY: 'hello'
  _SERVICE_ACCOUNT: 'demo-cb@gcp-az-prj-439316.iam.gserviceaccount.com'

serviceAccount: 'projects/gcp-az-prj-439316/serviceAccounts/demo-cb@gcp-az-prj-439316.iam.gserviceaccount.com'

steps:
  # Step 1: Fetch commit ID
  - name: 'alpine'
    id: 'fetch-commit-id'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache git && \
        COMMIT_ID=$(git rev-parse --short HEAD) && \
        echo "COMMIT_ID=${COMMIT_ID}" > /workspace/env_vars

  # Step 2: Load commit ID from env_vars file
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - . /workspace/env_vars && echo "Commit ID: $COMMIT_ID"

  # Step 3: Build the Docker image with the commit ID
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY/$_IMAGE_NAME:${COMMIT_ID}'
      - '.'

  # Step 4: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY/$_IMAGE_NAME:${COMMIT_ID}'

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '600s'
